version: "2.1.{build}"
image: Visual Studio 2019
branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

nuget:
  disable_publish_on_pr: true

# Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./IqOptionApi.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - ps: ./build/package.ps1

artifacts:
  - path: Build\Packages\*nupkg

# any cleanup in here
deploy:
  - provider: NuGet
    api_key:
      secure: PD+Mb+nDiji71lFSy6wzQr+k796j3KBXsZswzX0p+LBZ+orVn+yPI/soLlHxfexz
    skip_symbols: false
    artifact: /.*\.(nupkg|snupkg)/
    appveyor_repo_tag: true
    on:
      branch: master
